Repository infotexture/dita-bootstrap, pull requests merged in 2023-09, with the labels that each got.

#118 Add Bootstrap classes to Footer
  .github/dita-ot/footer.xml
  .github/dita-ot/theme.css
  Customization/xsl/topic.xsl
  README.md
  includes/bs-footer-example.xml
  insertParameters.xml
  plugin.xml
  sample/index.dita
Labels: enhancement, documentation

#122 Improve sidebar
  Customization/xsl/nav.xsl
  README.md
  build_dita2html5-bootstrap_template.xml
  css/collapsible-toc.css
  css/common-bootstrap.css
  css/side-toc.css
  includes/ftr.content.example.xml
  includes/ftr.sidebar.example.xml
  includes/hdr.navbar.default.xml
  includes/hdr.navbar.example.xml
  includes/hdr.sidebar.example.xml
  insertParameters.xml
  plugin.xml
  sample/index.dita
  sample/nav.dita
  xsl/html5-bootstrap.xsl
Labels: enhancement, documentation

#123 Add compact list group items.
  Customization/xsl/topic.xsl
  Customization/xsl/utility-classes.xsl
  sample/list-group.dita
Labels: enhancement, documentation

#124 Bootstrap 5.3.2
  Customization/xsl/nav.xsl
  css/collapsible-toc.css
  includes/bootstrap.hdf.rtl.xml
  includes/bootstrap.hdf.xml
  includes/bootstrap.icons.hdf.xml
  includes/script-only.hdf.xml
  package-lock.json
  package.json
Labels: dependencies

#121 Align documentation with unobstrusive.
  .github/dita-ot/header.xml
  sample/search-box.dita
  sample/src/search-box.png
  sample/src/search-complex.png
  sample/src/search-result.png
  sample/src/search-simple.png
Labels: documentation

#131 Add new topic on DITA Bootstrap Sass
  sample/button-group.dita
  sample/document.ditamap
  sample/index.dita
  sample/sass.dita
  sample/scrollspy.dita
  sample/utilities.dita
Labels: enhancement

#132 Update to Bootswatch 5.3.2
  includes/bootstrap.icons.hdf.xml
  includes/theme.hdf.xml
  package-lock.json
  package.json
Labels: dependencies
